# Generated by Django 5.1.6 on 2025-04-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionbatch',
            name='batch_number',
            field=models.CharField(default='BATCH-CA1D365D', max_length=50, unique=True),
        ),
    ]
