# Generated by Django 5.1.6 on 2025-04-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionbatch_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionbatch',
            name='batch_number',
            field=models.CharField(default='BATCH-B9D4093B', max_length=50, unique=True),
        ),
    ]
